FROM node:alpine as builder
WORKDIR /app
COPY package*.json /app
RUN cd /app && npm set progress=false && npm install
COPY . /app
RUN cd /app && npm run build

FROM nginx:alpine
RUN rm -rf /usr/share/nginx/html/*
COPY --from=builder app/dist/client /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
