version: '3.3'
services:
  meanbookmarkdb:
    image: mongo
    ports:
      - 27017:27017
  server:
    image: meanbookmarkserver:1.0.0
    build: server
    ports:
      - 3000:3000
    links:
      - meanbookmarkdb
  client:
    image: meanbookmarkapp:1.0.0
    build: client
    ports:
      - 4200:80